"""correct columns

Revision ID: 036588b5f49e
Revises: 5b5ba8867630
Create Date: 2018-09-04 10:10:18.738527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036588b5f49e'
down_revision = '5b5ba8867630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
